### ISSUE TITLE
Title centered?

### ISSUE THREAD

**Issue by edr17** [chyrta/AndroidOnboarder#10]
Hi,

Right now I have 5 onboarding pages and my 1-line titles are centered but my 2-line titles are left-aligned. I don't see an option to make the title appear centered always?
Can we make the title appear centered if the title is more than 1 line?

thanks
ed

**Comment by chyrta** [comment]
@eduardr It's definitely a good point. Will implement a method for controlling that behaviour.

**Comment by mbarta** [comment]
@chyrta, #13 submitted

**Comment by chyrta** [comment]
Will mark it as closed, as @mbarta's commit #13 merged.
