### ISSUE TITLE
NullPointerException at ViewPager

### ISSUE THREAD

**Issue by JovieBrett** [chyrta/AndroidOnboarder#3]
I'm getting a NullPointerException on ViewPager also please add on the tutorial on how to correctly set this as an intent first which will run the first time a user installs the app?

**Comment by chyrta** [comment]
@JovieBrett OK, a good improvement to do. I will create a wiki-page very soon.
About resolving an issue with NEP in ViewPager: 
1. Which Android version you use to testify all the things? 
2. It would be great if I can see the log with NEP. Can you provide it?

**Comment by chyrta** [comment]
The issue was resolved with the help of @joshuarose. New improvements in 0.6 version.

**Comment by chyrta** [comment]
The issue was resolved with the help of @joshuarose. New improvements in 0.6 version.
