### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by edr17** [chyrta/AndroidOnboarder#5]
Hi, thanks for this useful project.

I want to suggest some features also:
1) allow to set font size of title and description.
2) allow to set image as background.
3) allow to hide the skip button and rename the skip button.
4) allow to rename the finish button.

Thanks again!

**Comment by chyrta** [comment]
@eduardr Thanks for feedback!

**Comment by chyrta** [comment]
@eduardr 3 of 4 features from your suggestions were implemented 👍
