### ISSUE TITLE
Change app_name from my Application

### ISSUE THREAD

**Issue by jfbarragan** [chyrta/AndroidOnboarder#8]
Hello, 
Why when I implement the library, it automatically changes the name from my Application when I installed on my phone changes the original name by Android Onboarder.

Thanks,
Francisco.

**Comment by GrenderG** [comment]
Add `tools:replace="android:label"` in your `application`'s tag inside your `AndroidManifest.xml` file.

**Comment by chyrta** [comment]
@GrenderG Thanks for help as I haven't so much time to support the library 👍 
@jfbarragan I have already pushed a small fix for that issue c6adae1. Will appear in 0.7 version.

**Comment by packo6300** [comment]
> Añadir `tools:replace="android:label"`en su `application`'s etiqueta dentro de su `AndroidManifest.xml`archivo.

@GrenderG Hello, can you put a example on code? i try put them on my app manifest, but don't works!! 
Tanks!!
